version: '3.9'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"

